name: forja_trabajo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true  # Espacio después de los dos puntos
  ios: true     # Espacio después de los dos puntos
  image_path: "assets/logo_150.png"  # Formato correcto para un solo path

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo_300.png
    - assets/encuesta.png
    - assets/avatar.png
    - assets/avatar2.png
    - assets/avatar3.png
    - assets/electricista_trabajando.jpg
    - assets/funciones_del_plomero.jpg
    - assets/oficio_albañil.jpg
    - assets/oficio_mecanico.jpg
